series: Basic OpenGL with GLFW
title: Texturing a Cube
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Add textures to 3D geometry.
language: C++
tags:
  - Graphics
extra_resources:
connections:
  - series: Basic OpenGL with GLFW
    title: Drawing a Cube
  - series: Basic OpenGL with GLFW
    title: Textures